### ISSUE TITLE
demonstration just renders vertical red line

### ISSUE THREAD

**Issue by helgein** [BoboTiG/py-candlestick-chart#18]
WSL debian 11; 
pasted demonstration to mychart.py and commented out 5 lines containing "fnum".
Does not recognize current height, width of the terminal. 
Does not draw 5 candles but one single vertical red line.

cat /etc/issue;echo $TERM; python3 mychart.py | less -SR
Debian GNU/Linux 11 \n \l
xterm-256color
<img width="960" alt="chart" src="https://github.com/BoboTiG/py-candlestick-chart/assets/14905554/7e7c8b02-1d5c-415f-8c18-5b8528de25db">

xterm -fs 11 -fa DejaVuSansMono
cat /etc/issue;echo $TERM; python3 mychart.py
xterm
<img width="959" alt="chart1" src="https://github.com/BoboTiG/py-candlestick-chart/assets/14905554/bb08154f-495c-4a57-ac40-b7b8c2a05830">

**Comment by BoboTiG** [comment]
Demo code is to show potential of wjat can be done with the module.

For better code, try examples instead.
